# Generated by Django 5.1.4 on 2024-12-23 10:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100, verbose_name='Город')),
                ('street', models.CharField(max_length=100, verbose_name='Улица')),
                ('home', models.CharField(max_length=10, verbose_name='Номер дома')),
            ],
            options={
                'verbose_name': 'Адрес',
                'verbose_name_plural': 'Адреса',
                'db_table': 'addresses',
                'ordering': ['city', 'street', 'home'],
            },
        ),
        migrations.CreateModel(
            name='GoldStandard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата смены')),
                ('gold_standard', models.IntegerField(choices=[(750, 'ЗОЛОТО 750'), (585, 'ЗОЛОТО 585'), (500, 'ЗОЛОТО 500'), (375, 'ЗОЛОТО 375'), (925, 'СЕРЕБРО 925'), (875, 'СЕРЕБРО 875')], default=585, verbose_name='Проба')),
                ('price_rubles', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена в рублях')),
            ],
            options={
                'verbose_name': 'Цена на лом',
                'db_table': 'gold_standard',
                'ordering': ['gold_standard'],
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(default='default_username', max_length=100, unique=True, verbose_name='Имя пользователя')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='Email')),
                ('last_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Фамилия')),
                ('first_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя')),
                ('patronymic', models.CharField(blank=True, max_length=100, null=True, verbose_name='Отчество')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
                'db_table': 'custom_user',
                'ordering': ['username'],
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(choices=[('monday', 'Понедельник'), ('tuesday', 'Вторник'), ('wednesday', 'Среда'), ('thursday', 'Четверг'), ('friday', 'Пятница'), ('saturday', 'Суббота'), ('sunday', 'Воскресенье')], max_length=9, verbose_name='День недели')),
                ('opening_time', models.TimeField(verbose_name='Время открытия')),
                ('closing_time', models.TimeField(verbose_name='Время закрытия')),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='address_schedules', to='cashbox_app.address')),
            ],
            options={
                'verbose_name': 'Расписание',
                'db_table': 'schedule',
                'ordering': ['address'],
            },
        ),
        migrations.CreateModel(
            name='SecretRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата смены')),
                ('client', models.CharField(default='Новый клиент', max_length=50, verbose_name='Клиент')),
                ('nomenclature', models.CharField(max_length=50, verbose_name='Наименование')),
                ('gold_standard', models.IntegerField(choices=[(750, 'ЗОЛОТО 750'), (585, 'ЗОЛОТО 585'), (500, 'ЗОЛОТО 500'), (375, 'ЗОЛОТО 375'), (925, 'СЕРЕБРО 925'), (875, 'СЕРЕБРО 875')], default=585, verbose_name='Проба')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена за грамм')),
                ('weight_clean', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Чистый вес')),
                ('weight_fact', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Фактический вес')),
                ('sum', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Выдано денег')),
                ('converter585', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Конвертер 585 проба')),
                ('converter925', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Конвертер 925 проба')),
                ('not_standard', models.BooleanField(blank=True, default=False, null=True, verbose_name='Не стандарт')),
                ('status', models.CharField(choices=[('В ФИЛИАЛЕ', 'Local'), ('СОБРАНО', 'Gather'), ('ВЫДАНО', 'Issued')], default='В ФИЛИАЛЕ', max_length=15, verbose_name='Статус скупки')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Сотрудник смены')),
                ('id_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cashbox_app.address', verbose_name='Адрес')),
            ],
            options={
                'verbose_name': 'Скупка',
                'verbose_name_plural': 'Скупки',
                'db_table': 'secret_poom',
                'ordering': ['id_address'],
            },
        ),
        migrations.CreateModel(
            name='CashReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата смены')),
                ('cas_register', models.CharField(choices=[('BUYING_UP', 'Скупка'), ('PAWNSHOP', 'Ломбард'), ('TECHNIQUE', 'Техника')], max_length=10)),
                ('cash_balance_beginning', models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Остаток денежных средств в начале')),
                ('introduced', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, null=True, verbose_name='Внесено в кассу')),
                ('interest_return', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, null=True, verbose_name='Средства от процентов с залога, возврата выданных займов')),
                ('loans_issued', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, null=True, verbose_name='Выдано займов')),
                ('used_farming', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, null=True, verbose_name='На хоз. нужды, оплату труда')),
                ('boss_took_it', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, null=True, verbose_name='Выемка денежных средств руководителем')),
                ('cash_register_end', models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Остаток на конец дня')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Дата изменения')),
                ('status', models.CharField(choices=[('OPEN', 'Открыто'), ('CLOSED', 'Закрыто'), ('DRAFT', 'Черновик')], default='OPEN', max_length=10)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Сотрудник смены')),
                ('id_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cashbox_app.address', verbose_name='Адрес')),
            ],
            options={
                'verbose_name': 'Кассовый отчет',
                'verbose_name_plural': 'Кассовый отчеты',
                'db_table': 'cash_report',
                'ordering': ['shift_date'],
                'unique_together': {('shift_date', 'id_address', 'cas_register', 'cash_balance_beginning', 'introduced', 'interest_return', 'loans_issued', 'used_farming', 'boss_took_it', 'cash_register_end')},
            },
        ),
    ]
