# Generated by Django 5.0.7 on 2024-12-10 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cashbox_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="secretroom",
            name="status",
            field=models.CharField(
                choices=[
                    ("В ФИЛИАЛЕ", "Local"),
                    ("СОБРАНО", "Gather"),
                    ("ВЫДАНО", "Issued"),
                ],
                default="В ФИЛИАЛЕ",
                max_length=15,
                verbose_name="Статус скупки",
            ),
        ),
    ]
