# Generated by Django 5.0.4 on 2024-04-26 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cashbox_app', '0002_customuser_date_joined'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='date_joined',
        ),
    ]
