# Generated by Django 5.0.7 on 2024-09-17 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashbox_app', '0005_remove_customuser_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashreport',
            name='boss_took_it',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Выемка денежных средств руководителем'),
        ),
        migrations.AlterField(
            model_name='cashreport',
            name='interest_return',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Средства от процентов с залога, возврата выданных займов'),
        ),
        migrations.AlterField(
            model_name='cashreport',
            name='introduced',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Внесено в кассу'),
        ),
        migrations.AlterField(
            model_name='cashreport',
            name='loans_issued',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Выдано займов'),
        ),
        migrations.AlterField(
            model_name='cashreport',
            name='used_farming',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='На хоз. нужды, оплату труда'),
        ),
    ]
