# Generated by Django 5.0.7 on 2024-09-17 10:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashbox_app', '0006_alter_cashreport_boss_took_it_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashreport',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Сотрудник смены'),
        ),
        migrations.AlterField(
            model_name='cashreport',
            name='boss_took_it',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, null=True, verbose_name='Выемка денежных средств руководителем'),
        ),
        migrations.AlterField(
            model_name='cashreport',
            name='cash_balance_beginning',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Остаток денежных средств в начале'),
        ),
        migrations.AlterField(
            model_name='cashreport',
            name='cash_register_end',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Остаток на конец дня'),
        ),
        migrations.AlterField(
            model_name='cashreport',
            name='interest_return',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, null=True, verbose_name='Средства от процентов с залога, возврата выданных займов'),
        ),
        migrations.AlterField(
            model_name='cashreport',
            name='introduced',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, null=True, verbose_name='Внесено в кассу'),
        ),
        migrations.AlterField(
            model_name='cashreport',
            name='loans_issued',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, null=True, verbose_name='Выдано займов'),
        ),
        migrations.AlterField(
            model_name='cashreport',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Дата изменения'),
        ),
        migrations.AlterField(
            model_name='cashreport',
            name='used_farming',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, null=True, verbose_name='На хоз. нужды, оплату труда'),
        ),
    ]
