# Generated by Django 5.0.7 on 2024-11-02 12:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cashbox_app", "0009_schedule_address_schedules"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="address",
            options={"ordering": ["city", "street", "home"]},
        ),
        migrations.RemoveField(
            model_name="address",
            name="schedules",
        ),
        migrations.AddField(
            model_name="schedule",
            name="address",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="address_schedules",
                to="cashbox_app.address",
            ),
        ),
    ]
