# Generated by Django 5.0.7 on 2024-12-04 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cashbox_app", "0011_goldstandard_secretroom"),
    ]

    operations = [
        migrations.AlterField(
            model_name="secretroom",
            name="status",
            field=models.CharField(
                choices=[
                    ("LOCAL", "В ФИЛИАЛЕ"),
                    ("GATHER", "СОБРАНО"),
                    ("ISSUED", "ВЫДАНО"),
                ],
                default="LOCAL",
                max_length=15,
                verbose_name="Выдано денег",
            ),
        ),
    ]
