# Generated by Django 5.0.7 on 2024-12-04 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cashbox_app", "0013_alter_secretroom_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="secretroom",
            name="GoldStandard",
        ),
        migrations.RemoveField(
            model_name="secretroom",
            name="fio",
        ),
        migrations.AddField(
            model_name="secretroom",
            name="client",
            field=models.CharField(
                default="Новый клиент", max_length=50, verbose_name="Клиент"
            ),
        ),
        migrations.AddField(
            model_name="secretroom",
            name="gold_standard",
            field=models.CharField(
                choices=[
                    ("750gold", "750gold"),
                    ("585goldN", "Не стандарт"),
                    ("585gold", "585gold"),
                    ("500gold", "500gold"),
                    ("375gold", "375gold"),
                    ("925silvers", "925silvers"),
                    ("875silvers", "875silvers"),
                ],
                default="gold585",
                max_length=15,
                verbose_name="Проба",
            ),
        ),
        migrations.AlterField(
            model_name="secretroom",
            name="nomenclature",
            field=models.CharField(max_length=50, verbose_name="Наименование"),
        ),
    ]
