# Generated by Django 5.0.7 on 2024-12-04 13:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "cashbox_app",
            "0014_remove_secretroom_goldstandard_remove_secretroom_fio_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="secretroom",
            name="author",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Сотрудник смены",
            ),
        ),
    ]
